basePath: /
definitions:
  models.User:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 3
        type: string
    required:
    - name
    - password
    - username
    type: object
  utils.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  description: API desenvolvida para projeto academico
  title: API Mensina
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with the provided details
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Create a new user
      tags:
      - Users
swagger: "2.0"
